site_name: XKPASSWD User Docs
site_url: https://xkpasswd.net/userdocs
nav:
  - About: about.md
  - Home: index.md
  - User Guide: user-guide.md  
  - Help the Project: help-xkpasswd.md
  - XKCD and XKPASSWD: xkcd-comic.md

theme: 
  name: mkdocs
  navigation_depth: 4
  # nav_style: light
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

extra_css:
  - docs_dir/style.css

